language: "ruby"

rvm:
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
  - "jruby"
  - "rbx"

sudo: false

install:
  - bundle install --retry=3

matrix:
  include:
    - rvm: "2.2"
      gemfile: "gemfiles/Gemfile.uuidtools.x"
env:
  global:
    - CODECLIMATE_REPO_TOKEN=f06667b968b44c85d8bacf7321b323574188f6771d0d3534e0cb9ddaade23dd7
